In [129]:
import numpy as np
import pandas as pd

In [135]:
df=pd.read_csv('/content/id.csv')
df

Name  house_no
0  md abdur rahman         1
1  md Tahmid hasan         2
2      utsha shaha         3
3     badhan shaha         4
4     sayem hosain         5
5    mominul isalm         6

In [5]:
df.head()

Name  house_no
0  md abdur rahman         1
1  md Tahmid hasan         2
2      utsha shaha         3
3     badhan shaha         4
4     sayem hosain         5

In [6]:
df.ndim
df

Name  house_no
0  md abdur rahman         1
1  md Tahmid hasan         2
2      utsha shaha         3
3     badhan shaha         4
4     sayem hosain         5
5    mominul isalm         6

In [136]:
df.describe

<bound method NDFrame.describe of               Name  house_no
0  md abdur rahman         1
1  md Tahmid hasan         2
2      utsha shaha         3
3     badhan shaha         4
4     sayem hosain         5
5    mominul isalm         6>

In [7]:
df.isnull().any()


Name        False
house_no    False
dtype: bool

In [8]:
df.shape 

(6, 2)

In [10]:
df.duplicated().sum()

0

In [15]:
x=df[['Name']]
x

Name
0  md abdur rahman
1  md Tahmid hasan
2      utsha shaha
3     badhan shaha
4     sayem hosain
5    mominul isalm

In [16]:
y=df[['house_no']]
y

house_no
0         1
1         2
2         3
3         4
4         5
5         6

In [22]:
df['house_no'].value_counts()

6    1
5    1
4    1
3    1
2    1
1    1
Name: house_no, dtype: int64

In [24]:
df.isnull().sum()

Name        0
house_no    0
dtype: int64

In [81]:
X=df.Name.values
X

array(['md abdur rahman', 'md Tahmid hasan', 'utsha shaha',
       'badhan shaha', 'sayem hosain', 'mominul isalm'], dtype=object)

In [82]:
Y=df.house_no.values
Y

array([1, 2, 3, 4, 5, 6])

In [83]:
from sklearn.model_selection import train_test_split

In [103]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.6)

In [104]:
from sklearn.feature_extraction.text import CountVectorizer

In [105]:
cv=CountVectorizer()
a=cv.fit_transform(Xtrain)

In [106]:
a.toarray()

array([[0, 1, 1, 0],
       [1, 0, 0, 1]])

In [107]:
from sklearn.naive_bayes import MultinomialNB

In [108]:
model=MultinomialNB()
model.fit(a,Ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [109]:
x_test=cv.transform(Xtest)

In [110]:
x_test.toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [116]:
model.score(x_test,Ytest)

0.0